<?xml version="1.0" encoding="utf-8"?><Database Name="FlowersDB" Class="FlowersDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-PLG7HV2\SQLEXPRESS;Initial Catalog=FlowersDB;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="FlowersDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.FlowersShop" Member="FlowersShops">
    <Type Name="FlowersShop">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FlowersName" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ImagePath" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TagContent" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TypeColumn" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>