#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flowers
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="FlowersDB")]
	public partial class FlowersDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertFlowersShop(FlowersShop instance);
    partial void UpdateFlowersShop(FlowersShop instance);
    partial void DeleteFlowersShop(FlowersShop instance);
    #endregion
		
		public FlowersDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["FlowersDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public FlowersDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FlowersDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FlowersDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FlowersDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<FlowersShop> FlowersShops
		{
			get
			{
				return this.GetTable<FlowersShop>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FlowersShop")]
	public partial class FlowersShop : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _FlowersName;
		
		private string _ImagePath;
		
		private string _TagContent;
		
		private System.Nullable<int> _TypeColumn;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnFlowersNameChanging(string value);
    partial void OnFlowersNameChanged();
    partial void OnImagePathChanging(string value);
    partial void OnImagePathChanged();
    partial void OnTagContentChanging(string value);
    partial void OnTagContentChanged();
    partial void OnTypeColumnChanging(System.Nullable<int> value);
    partial void OnTypeColumnChanged();
    #endregion
		
		public FlowersShop()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlowersName", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string FlowersName
		{
			get
			{
				return this._FlowersName;
			}
			set
			{
				if ((this._FlowersName != value))
				{
					this.OnFlowersNameChanging(value);
					this.SendPropertyChanging();
					this._FlowersName = value;
					this.SendPropertyChanged("FlowersName");
					this.OnFlowersNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImagePath", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string ImagePath
		{
			get
			{
				return this._ImagePath;
			}
			set
			{
				if ((this._ImagePath != value))
				{
					this.OnImagePathChanging(value);
					this.SendPropertyChanging();
					this._ImagePath = value;
					this.SendPropertyChanged("ImagePath");
					this.OnImagePathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TagContent", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string TagContent
		{
			get
			{
				return this._TagContent;
			}
			set
			{
				if ((this._TagContent != value))
				{
					this.OnTagContentChanging(value);
					this.SendPropertyChanging();
					this._TagContent = value;
					this.SendPropertyChanged("TagContent");
					this.OnTagContentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeColumn", DbType="Int")]
		public System.Nullable<int> TypeColumn
		{
			get
			{
				return this._TypeColumn;
			}
			set
			{
				if ((this._TypeColumn != value))
				{
					this.OnTypeColumnChanging(value);
					this.SendPropertyChanging();
					this._TypeColumn = value;
					this.SendPropertyChanged("TypeColumn");
					this.OnTypeColumnChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
